<a href="https://colab.research.google.com/github/bcury/Machine-Learning-Projects/blob/main/AI_RNAKeras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, f1_score, recall_score, confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [3]:
df = pd.read_csv("Churn.csv", sep=";")
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0,1,1,1,10134888,1
1,608,Spain,Female,41,1,8380786,1,0,1,11254258,0
2,502,France,Female,42,8,1596608,3,1,0,11393157,1
3,699,France,Female,39,1,0,2,0,0,9382663,0
4,850,Spain,Female,43,2,12551082,1,1,1,790841,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0,2,1,0,9627064,0
9996,516,France,Male,35,10,5736961,1,1,1,10169977,0
9997,709,France,Female,36,7,0,1,0,1,4208558,1
9998,772,Germany,Male,42,3,7507531,2,1,0,9288852,1
9999,792,France,Female,28,4,13014279,1,1,0,3819078,0

In [4]:
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [5]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0,1,1,1,10134888
1,608,Spain,Female,41,1,8380786,1,0,1,11254258
2,502,France,Female,42,8,1596608,3,1,0,11393157
3,699,France,Female,39,1,0,2,0,0,9382663
4,850,Spain,Female,43,2,12551082,1,1,1,790841
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0,2,1,0,9627064
9996,516,France,Male,35,10,5736961,1,1,1,10169977
9997,709,France,Female,36,7,0,1,0,1,4208558
9998,772,Germany,Male,42,3,7507531,2,1,0,9288852
9999,792,France,Female,28,4,13014279,1,1,0,3819078

In [6]:
standarscaler = StandardScaler()
numerical = X.select_dtypes(include=['int64','float64']).columns
X[numerical] = standarscaler.fit_transform(X[numerical])

In [7]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,France,Female,0.293517,-1.041760,-1.110553,-0.911583,0.646092,0.970243,0.170614
1,-0.440036,Spain,Female,0.198164,-1.387538,0.222782,-0.911583,-1.547768,0.970243,0.353281
2,-1.536794,France,Female,0.293517,1.032908,-0.856542,2.527057,0.646092,-1.030670,0.375948
3,0.501521,France,Female,0.007457,-1.387538,-1.110553,0.807737,-1.547768,-1.030670,0.047859
4,2.063884,Spain,Female,0.388871,-1.041760,0.886252,-0.911583,0.646092,0.970243,-1.354223
...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,France,Male,0.007457,-0.004426,-1.110553,0.807737,0.646092,-1.030670,0.087743
9996,-1.391939,France,Male,-0.373958,1.724464,-0.197835,-0.911583,0.646092,0.970243,0.176340
9997,0.604988,France,Female,-0.278604,0.687130,-1.110553,-0.911583,-1.547768,0.970243,-0.796492
9998,1.256835,Germany,Male,0.293517,-0.695982,0.083852,0.807737,0.646092,-1.030670,0.032551
9999,1.463771,France,Female,-1.041433,-0.350204,0.959944,-0.911583,0.646092,-1.030670,-0.860051

In [8]:
labelencoder = LabelEncoder()
categorical = X.select_dtypes(include='object').columns
for col in categorical:
  X[col] = labelencoder.fit_transform(X[col])

In [9]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,0,0,0.293517,-1.041760,-1.110553,-0.911583,0.646092,0.970243,0.170614
1,-0.440036,2,0,0.198164,-1.387538,0.222782,-0.911583,-1.547768,0.970243,0.353281
2,-1.536794,0,0,0.293517,1.032908,-0.856542,2.527057,0.646092,-1.030670,0.375948
3,0.501521,0,0,0.007457,-1.387538,-1.110553,0.807737,-1.547768,-1.030670,0.047859
4,2.063884,2,0,0.388871,-1.041760,0.886252,-0.911583,0.646092,0.970243,-1.354223
...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0,1,0.007457,-0.004426,-1.110553,0.807737,0.646092,-1.030670,0.087743
9996,-1.391939,0,1,-0.373958,1.724464,-0.197835,-0.911583,0.646092,0.970243,0.176340
9997,0.604988,0,0,-0.278604,0.687130,-1.110553,-0.911583,-1.547768,0.970243,-0.796492
9998,1.256835,1,1,0.293517,-0.695982,0.083852,0.807737,0.646092,-1.030670,0.032551
9999,1.463771,0,0,-1.041433,-0.350204,0.959944,-0.911583,0.646092,-1.030670,-0.860051

In [10]:
X_treino, X_teste, y_treino, y_teste = train_test_split(X,y, test_size=0.3, random_state=0)

In [11]:
modelo = Sequential()
modelo.add(Dense(units=64, activation='relu', input_dim=X_treino.shape[1]))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=32, activation='relu'))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=64, activation='relu'))
modelo.add(Dropout(0.4))
modelo.add(Dense(units=1, activation='sigmoid'))

In [12]:
modelo.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
modelo.fit(X_treino, y_treino, epochs=50, batch_size=32)

Epoch 1/50
219/219 [==============================] - 1s 1ms/step - loss: 0.5198 - accuracy: 0.7683
Epoch 2/50
219/219 [==============================] - 0s 1ms/step - loss: 0.4637 - accuracy: 0.8006
Epoch 3/50
219/219 [==============================] - 0s 1ms/step - loss: 0.4473 - accuracy: 0.8051
Epoch 4/50
219/219 [==============================] - 0s 1ms/step - loss: 0.4342 - accuracy: 0.8126
Epoch 5/50
219/219 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8227
Epoch 6/50
219/219 [==============================] - 0s 1ms/step - loss: 0.4029 - accuracy: 0.8341
Epoch 7/50
219/219 [==============================] - 0s 1ms/step - loss: 0.4024 - accuracy: 0.8350
Epoch 8/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3917 - accuracy: 0.8401
Epoch 9/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3930 - accuracy: 0.8434
Epoch 10/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3874 - accuracy: 0.8426
Epoch 11/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3853 - accuracy: 0.8409
Epoch 12/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3814 - accuracy: 0.8441
Epoch 13/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3794 - accuracy: 0.8441
Epoch 14/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3771 - accuracy: 0.8494
Epoch 15/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3708 - accuracy: 0.8497
Epoch 16/50
219/219 [==============================] - 0s 2ms/step - loss: 0.3722 - accuracy: 0.8480
Epoch 17/50
219/219 [==============================] - 0s 2ms/step - loss: 0.3734 - accuracy: 0.8520
Epoch 18/50
219/219 [==============================] - 0s 2ms/step - loss: 0.3774 - accuracy: 0.8507
Epoch 19/50
219/219 [==============================] - 0s 2ms/step - loss: 0.3668 - accuracy: 0.8496
Epoch 20/50
219/219 [==============================] - 0s 2ms/step - loss: 0.3728 - accuracy: 0.8469
Epoch 21/50
219/219 [==============================] - 0s 2ms/step - loss: 0.3672 - accuracy: 0.8531
Epoch 22/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3693 - accuracy: 0.8517
Epoch 23/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3645 - accuracy: 0.8524
Epoch 24/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3621 - accuracy: 0.8566
Epoch 25/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3644 - accuracy: 0.8526
Epoch 26/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3643 - accuracy: 0.8554
Epoch 27/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3594 - accuracy: 0.8526
Epoch 28/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3640 - accuracy: 0.8520
Epoch 29/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3627 - accuracy: 0.8519
Epoch 30/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3543 - accuracy: 0.8536
Epoch 31/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3616 - accuracy: 0.8541
Epoch 32/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3577 - accuracy: 0.8549
Epoch 33/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3516 - accuracy: 0.8569
Epoch 34/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3589 - accuracy: 0.8569
Epoch 35/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3605 - accuracy: 0.8564
Epoch 36/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3516 - accuracy: 0.8569
Epoch 37/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3534 - accuracy: 0.8587
Epoch 38/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3552 - accuracy: 0.8606
Epoch 39/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3531 - accuracy: 0.8599
Epoch 40/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3569 - accuracy: 0.8591
Epoch 41/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3514 - accuracy: 0.8600
Epoch 42/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3507 - accuracy: 0.8600
Epoch 43/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3529 - accuracy: 0.8586
Epoch 44/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3526 - accuracy: 0.8581
Epoch 45/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3554 - accuracy: 0.8581
Epoch 46/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3453 - accuracy: 0.8613
Epoch 47/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3502 - accuracy: 0.8547
Epoch 48/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3481 - accuracy: 0.8623
Epoch 49/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3508 - accuracy: 0.8604
Epoch 50/50
219/219 [==============================] - 0s 1ms/step - loss: 0.3516 - accuracy: 0.8609

In [13]:
previsoes = modelo.predict(X_teste)
previsoes

94/94 [==============================] - 0s 778us/step

array([[0.2579612 ],
       [0.25235504],
       [0.20586854],
       ...,
       [0.07842771],
       [0.11730575],
       [0.63954186]], dtype=float32)

In [14]:
y_pred = (previsoes > 0.5).astype('int32')
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int32)

In [15]:
print('Acurácia: ', accuracy_score(y_teste, y_pred))
print('F1: ', f1_score(y_teste, y_pred))
print('Recall: ', recall_score(y_teste, y_pred))
print('Matriz de Confusão: ', confusion_matrix(y_teste, y_pred))

Acurácia:  0.8633333333333333
F1:  0.594059405940594
Recall:  0.4830917874396135
Matriz de Confusão:  [[2290   89]
 [ 321  300]]